#!/bin/bash
cp candela_show.py /usr/local/bin/candela_show.py
cp logo_candela.png /usr/local/share/logo_candela.png
cp Candela\ Show.desktop /etc/ /etc/guest-session/skel/Escritorio/Candela\ Show.desktop
